#!/bin/bash

DIR="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd )"
#echo "${DIR}"
tool="dummy"
root="dummy"
# shellcheck source=/dev/null
source "${DIR}/../.env"

rm -f "${DIR}/pkgs.log"

# Check if exactly one parameter is provided
if [[ $# -ne 1 ]]; then
    fatal "Usage: install_package <package_name>" 253
fi

package_name="$1"

# Define the sources directory
pkgs_dir="${DIR}/pkgs"

NOW="$(/usr/bin/date +%Y%m%d-%H%M%S)"
LOGIN="$(/usr/bin/id -un)"

logs="${DIR}/logs"
tool_pkgs="${tool}/pkgs"
mkdir -p "${logs}"

PATH_LOG="${logs}/${LOGIN}-$(basename "$0" .bash)-${NOW}.pkgs.log"
REL_PATH_LOG="logs/${LOGIN}-$(basename "$0" .bash)-${NOW}.pkgs.log"
rm -f "${DIR}/pkgs.log"
ln -nfs "${REL_PATH_LOG}" "${DIR}/pkgs.log"

info "Script Execution DIR '${DIR}'"
ok "Logging execution in '$PATH_LOG' (ln -nfs '${DIR}/pkgs.log')"

function displayLog() {
    res=$?
    if [[ ${res} != 0 ]]; then tail -15 "${DIR}/pkgs.log" >&3; fi
    /usr/bin/date >&3
}
trap displayLog EXIT

cd "${DIR}" || fatal "unable to access '${DIR}'" 111

# shellcheck source=/dev/null
source "${DIR}/../echos/echoslog"
exec 3>&2
exec 1> "$PATH_LOG"
exec 2>&1

set -o xtrace

function getArg() {
    local search_param="$1"
    shift
    for param in "$@"; do
        if [[ "$param" == "$search_param"  || "$param" == "$search_param="* ]]; then
            return 0
        fi
    done
    return 1
}


# main: Acts as the central execution point, orchestrating the overall setup process including dependency checks, installations, and environmental configurations, ensuring the script achieves its purpose of preparing the environment or updating software as required.
function main() {

    info "main: Start install package '${package_name} at '${NOW}' for root='${root}'"
    # shellcheck disable=SC2154
    cd "${root}" || fatal "Unable to access pkgs_dir '${root}'" 22

    local pkg_base
    pkg_base=$(pkg_base "${package_name}")
    local i_log
    i_log="${tool}/logs/install_package.log"
    rm -f "${i_log}"
    local m_log
    m_log="${tool}/logs/mirror_package.log"
    rm -f "${m_log}"
    if ! check_flag_exists "${package_name}" "installed"; then
        ( install_package ) 2>&1 | tee -a "${i_log}"
        if check_flag_exists "${package_name}" "installed" && [[ -e "${i_log}" ]]; then
            cat "${i_log}" > "${pkg_base}.installed"
        else
            fatal "Unable to install '${package_name}'" 28
        fi
    fi
    if ! check_flag_exists "${package_name}" "mirrored"; then
        ( list_archive_content_to_mirror "${package_name}" ) 2>&1 | tee -a "${m_log}"
        if check_flag_exists "${package_name}" "mirrored" && [[ -e "${m_log}" ]]; then
            echo "-------------------">> "${pkg_base}.installed.mirrored"
            cat "${m_log}" >> "${pkg_base}.installed.mirrored"
        else
            fatal "Unable to mirror '${package_name}'" 29
        fi
    fi
    post_install "${package_name}"
    return $?
}

pkg_base() {
    local pkg_base
    # Example: extracting the package name base without its extension
    if [[ "${package_name}" =~ \.rpm$ ]]; then
        pkg_base="${package_name%.rpm}"
    elif [[ "${package_name}" =~ \.tar\.gz$ ]]; then
        pkg_base="${package_name%.tar.gz}"
    elif [[ "${package_name}" =~ \.xz$ ]]; then
        pkg_base="${package_name%.xz}"
    else
        fatal "Unsupported package extension for '${package_name}'" 99
    fi
    echo "${pkg_base}"
}

post_install() {
    local package_name="$1"
    if [[ "$package_name" =~ ^binutils-[0-9] ]]; then
        if [[ ! -e "${root}/usr/bin/ld" ]]; then
            ln -nfs "ld.bfd" "${root}/usr/bin/ld"
        fi
    fi
}

check_flag_exists() {
    local pkg="$1"
    local flag_suffix="$2"
    local pattern="${pkg%.rpm}*${flag_suffix}*"
    cd ${tool_pkgs} || fatal "Unable to access pkgs_dir '${tool_pkgs}'" 32
    shopt -s nullglob
    # shellcheck disable=SC2206
    local flags=( ${pattern} )
    shopt -u nullglob
    if (( ${#flags[@]} > 0 )); then
        info "A file matching '${pattern}' already exists in '${tool_pkgs}'"
        ok "'${pkg}' already '${flag_suffix}' in '${tool_pkgs}'"
        cd "${root}" || fatal "Unable to access pkgs_dir '${root}'" 32
        return 0
    fi
    cd "${root}" || fatal "Unable to access pkgs_dir '${root}'" 33
    return 1
}

function install_package() {

    local pkg_base
    pkg_base=$(pkg_base "${package_name}")
    local flag="${tool_pkgs}/${pkg_base}.installed"
    if [[ "${package_name%.rpm}" != "${package_name}" ]]; then
        if ! rpm2cpio "${pkgs_dir}/${package_name}" | cpio -idmv; then fatal "Unable to install '${package_name}'" 2; fi
    elif [[ "${package_name%.xz}" != "${package_name}" ]]; then
        if ! xzcat "${pkgs_dir}/${package_name}" > "${package_name%.xz,,}"; then fatal "Unable to unxz '${package_name}'" 4; fi
        chmod 755 "${package_name%.xz,,}"
    elif [[ "${package_name%.tar.gz}" != "${package_name}" ]]; then
        if ! tar xpvf "${pkgs_dir}/${package_name}"; then fatal "Unable to untar gz '${package_name}'" 5; fi
    else
        fatal "unknown extension for archive '${package_name}'" 11
    fi
    touch "${flag}" || fatal "Unable to create flag file '${flag}'" 3
    ok "'${flag}' installed in '${tool_pkgs}'"

}

list_archive_content_to_mirror() {
    local archive="$1"
    local pkg_file="${pkgs_dir}/${archive}"
    local clean_ldd=0

    if [[ ! -e "${pkg_file}" ]]; then
        fatal "Archive file '${pkg_file}' not found" 1
    fi

    local pkg_base
    pkg_base=$(pkg_base "${package_name}")

    info "Listing contents of archive '${archive}':"
    if [[ "${archive%.rpm}" != "${archive}" ]]; then
        # Open file descriptor 8 with the command output, ensuring the while read runs in the current shell.
        exec 9< <(rpm2cpio "${pkg_file}" | cpio -itv)
        while IFS= read -r line <&9 || [ -n "$line" ]; do
            # Process each line (you can add custom processing here)
            # info "call mirror_system_executable '${line}' with clean_ldd='${clean_ldd}'"
            if ! mirror_system_executable "${line}"; then clean_ldd=1; fi
        done
        exec 9<&-
    elif [[ "${archive%.tar.gz}" != "${archive}" ]]; then
        tar tzvf "${pkg_file}" | while IFS= read -r line; do
            # Process each line (custom processing can be added here)
            info "tar.gz contains: ${line}"
        done
    elif [[ "${archive%.xz}" != "${archive}" ]]; then
        # Assuming it's a tar.xz archive
        if file "${pkg_file}" | grep -qi "tar archive"; then
            tar --xz -tzvf "${pkg_file}" | while IFS= read -r line; do
                info "tar.xz contains: ${line}"
            done
        else
            fatal "Unsupported xz archive type for '${archive}'" 1
        fi
    else
        fatal "Unknown archive extension for '${archive}'" 11
    fi

    #info "Final clean_ldd='${clean_ldd}'"
    if [[ "${clean_ldd}" != "0" ]]; then
        fatal "Some files in the archive have absolute system paths or unresolved paths" 199
    fi

    mv "${tool_pkgs}/${pkg_base}.installed" "${tool_pkgs}/${pkg_base}.installed.mirrored" || fatal "Unable to rename flag file '${pkg_base}.installed' to '${tool_pkgs}/${pkg_base}.installed.mirrored'" 12

}

mirror_system_executable() {
    local src_line="$1"
    # Remove everything before the first '/' and prepend '/' (if not already)
    local src_file="/${src_line#*/}"
    local ret=0

    # Check that src_file exists and is a regular file (not a symlink)
    if [[ -f "${src_file}" && ! -L "${src_file}" ]]; then
        # Construct the destination path by prefixing the current folder path.
        # For example, for /usr/bin/unzipsfx, it will be copied to ./usr/bin/unzipsfx
        task "Must copy '${src_file}' to mirror folder '$(pwd)'"
        local dest_file="./${src_file#/}"  # removes leading /
        local dest_dir
        dest_dir=$(dirname "${dest_file}")
        mkdir -p "${dest_dir}" || fatal "Unable to create directory '${dest_dir}'" 31

        local cp_output
        cp_output=$(cp "${src_file}" "${dest_file}" 2>&1)
        rc=$?
        if [ $rc -ne 0 ]; then
            if echo "$cp_output" | grep -qi "Permission denied"; then
                warning "Permission denied copying '${src_file}' to '${dest_file}', skipping marker creation"
                return 0
            else
                fatal "Unable to copy '${src_file}' to '${dest_file}': ${cp_output}" 32
            fi
        fi
        # Create a dummy file to indicate the file was copied
        touch "${dest_file}.copied" || fatal "Unable to create marker file '${dest_file}.copied'" 33
        info "Copied '${src_file}' to '${dest_file}' and created marker file '${dest_file}.copied'"
    else
        # info "No action: '${src_file}' either does not exist, is not a regular file, or is a symlink."
        if [[  -f "./${src_file#/}" && ! -L "./${src_file#/}" ]]; then
            if ! check_ldd "./${src_file#/}"; then ret=1; fi
        fi
    fi

    return ${ret}
}

contains_any() {
    local line="$1"
    shift
    for token in "$@"; do
        if [[ "$line" == *"$token"* ]]; then
            return 0
        fi
    done
    return 1
}

check_ldd() {
    local file="$1"

    # If the file name includes ' -> ', treat it as a symlink and skip ldd check.
    local exclude_tokens=(" -> " " => " "share/man" "share/doc" "share/licenses")
    if contains_any "${file}" "${exclude_tokens[@]}"; then
        return 0
    fi

    # If the file extension is h, hpp, or similar, no need to run ldd
    local ext="${file##*.}"
    case "$ext" in
        h|hpp|c|so|bz2|o|a|mo|gz|1.gz|LIB|pc)
            # info "'$file' is a header file; skipping ldd check"
            return 0
            ;;
    esac
    local output ret
    # Run ldd and capture output and exit code.
    output=$(ldd "$file" 2>&1)
    ret=$?
    if [ $ret -ne 0 ]; then
        # If ldd failed because the file is not a dynamic executable, we're done.
        if echo "$output" | grep -q "not a dynamic executable"; then
            info "'$file' is not a dynamic executable: no ldd check needed"
            return 0
        else
            warning "ldd unexpectedly failed for '$file': '${output}'"
            return $ret
        fi
    fi

    # Exclude list: if a line contains any of these strings, skip further tests.
    local exclude_tokens=("libm" "libc" "libdl" "ld-linux" "linux-vdso" "liboneagentproc")
    while IFS= read -r line || [ -n "$line" ]; do
        # If the line contains a '?' character, warn about an unresolved path.
        if [[ "$line" == *"?"* ]]; then
            warning "Unresolved path in ldd output: '$line'"
            ret=1
            continue
        fi

        # If the line includes any of the exclude tokens, do nothing.
        if contains_any "$line" "${exclude_tokens[@]}"; then
            continue
        fi

        # Check for an absolute system path. We look for a slash prefixed word.
        if [[ "${line}" =~ (^|[[:space:]])(/[^[:space:]]+) ]]; then
            if [[ "${line}" =~ [[:space:]]*(/[^[:space:]]+) ]]; then
                abs_path="${BASH_REMATCH[1]}"
                if [[ -e "${root}${abs_path}" || -e "${root}/usr${abs_path}" ]]; then
                    continue # Skip if the path exists
                fi
            fi
            warning "Absolute system path detected in ldd output: '$line' for file '${file}'"
            ret=1
        fi
    done <<< "${output}"
    return $ret
}

# if one of the parameter is "--reconfigure", shift, and set reconfigure=true, then pass the rest to main
main "$@"
res=$?
# echo "res='${res}'" >&3
if [[ ${res} != 0 ]]; then
    exit "${res}"
fi
ok "All done"