#!/bin/bash

DIR="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd )"
#echo "${DIR}"
# shellcheck source=/dev/null
source "${DIR}/../.env"
# shellcheck source=/dev/null
source "${DIR}/../echos/echos"
# shellcheck source=/dev/null
source "${DIR}/../bin/properties.sh"

rm -f "${DIR}/pkgs.log"

# Check if exactly one parameter is provided
if [[ $# -ne 2 ]]; then
    fatal "Usage: install_package <package_name>" 253
fi

package_name="$1"

# Define the sources directory
pkgs_dir="${DIR}/pkgs"


# Define the installation folder
sys_folder="${DIR}/sys"
mkdir -p "$sys_folder"

NOW="$(/usr/bin/date +%Y%m%d-%H%M%S)"
LOGIN="$(/usr/bin/id -un)"

logs="${DIR}/logs"
mkdir -p "${logs}"

PATH_LOG="${logs}/${LOGIN}-$(basename "$0" .bash)-${NOW}.pkgs.log"
ln -nfs "${PATH_LOG}" "${DIR}/pkgs.log"

info "Script Execution DIR '${DIR}'"
ok "Logging execution in '$PATH_LOG' (ln -nfs '${DIR}/pkgs.log')"

function displayLog() {
    res=$?
    if [[ ${res} != 0 ]]; then tail -15 "${DIR}/pkgs.log" >&3; fi
    /usr/bin/date >&3
}
trap displayLog EXIT

cd "${DIR}" || fatal "unable to access '${DIR}'" 111

# shellcheck source=/dev/null
source "${DIR}/../echos/echoslog"
exec 3>&2
exec 1> "$PATH_LOG"
exec 2>&1

set -o xtrace

function getArg() {
    local search_param="$1"
    shift
    for param in "$@"; do
        if [[ "$param" == "$search_param"  || "$param" == "$search_param="* ]]; then
            return 0
        fi
    done
    return 1
}


# main: Acts as the central execution point, orchestrating the overall setup process including dependency checks, installations, and environmental configurations, ensuring the script achieves its purpose of preparing the environment or updating software as required.
function main() {
    info "main: Start install package '${package_name} at '${NOW}'"
    # shellcheck disable=SC2154
    cd "${pkgs_dir}" || fatal "Unable to access pkgs_dir '${pkgs_dir}'" 22
    pwd
    return $?
}

# if one of the parameter is "--reconfigure", shift, and set reconfigure=true, then pass the rest to main
main "$@"
res=$?
# echo "res='${res}'" >&3
if [[ ${res} != 0 ]]; then
    exit "${res}"
fi
ok "All done"