# SSH_CONFIG_ENTRY=a SSH entre
# hostname=a hostname
# cplx_path=a path for cplx
services=git,python,mpdecimal,openssl111,openldap,curl,libpsl,libunistring,libidn2,openssl3,pass,pinentry,libgpg-error,glibc,gcc,flex2,make4,automake116
tools_to_recompile=git,python,mpdecimal,openssl111,openldap,curl,libpsl,libunistring,libidn2,openssl3,pass,pinentry,libgpg-error,glibc,gcc,flex2,make4,automake116
python_repository=python/cpython
centos_8_x86_64_pkgs_url=https://vault.centos.org/8-stream/BaseOS/x86_64/os/Packages/,https://download.fedora.devel.redhat.com/pub/archive/epel/8.9-2024-05-22/Everything/x86_64/Packages/[L]/
rhel_7_9_x86_64_pkgs_url=https://dl.rockylinux.org/vault/centos/7.9.2009/updates/x86_64/Packages/
#or
rhel_7_9_x86_64_pkgs_url=https://mirror.chpc.utah.edu/pub/centos/7/os/x86_64/Packages/
# or
rhel_7_9_x86_64_pkgs_url=https://buildlogs.centos.org/centos/7/os/x86_64-latest/Packages/
# or
rhel_7_9_x86_64_pkgs_url=https://archives.fedoraproject.org/pub/archive/epel/7.2019-05-29/x86_64/Packages/p/
# RHEL 9.6:
rhel_9_6_x86_64_pkgs_url=https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/,https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/,https://copr-be.cloud.fedoraproject.org/results/decisivinc/CentOS_RPMS/epel-9-x86_64/08200354-gdbm/

SSH_CONFIG_ENTRY=<your ssh entry>
hostname=<your hostname>
cplx_path=/home/<a user>/cplx (or any other folder name or pathname)
architecture= the result of source /etc/os-release; printf "%s_%s_%s" $ID $VERSION_ID $(uname -m)
