no-grab
pinentry-program ${HOME}/tools/git/root/usr/bin/pinentry-tty
default-cache-ttl 86400
max-cache-ttl 86400
allow-loopback-pinentry
debug-level basic
log-file /home/upipdfs01/tools/certs/gpg.log
