#!/bin/bash

DIR="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd )"
#echo "${DIR}"
properties_file="dummy"
# shellcheck source=/dev/null
source "${DIR}/../.env"

# Check if exactly at least two parameter is provided
if [[ $# -lt 2 ]]; then
  fatal "Usage: setup <tool_name> <version>" 1
fi

tool="$1"
version="$2"

if [[ -z "$services" ]]; then
    fatal "No services found in the properties file '${properties_file}'" 1
fi

# Convert the comma-separated services into an array
IFS=',' read -r -a service_array <<< "$services"

# Flag to indicate if the tool is valid
valid=false

# Iterate through the services to check for a match
for service in "${service_array[@]}"; do
    if [[ "$service" == "$tool" ]]; then
        valid=true
        break
    fi
done

# If the tool is not valid, use fatal to exit with an error message
if [[ "$valid" == false ]]; then
    fatal "Invalid tool name: '${tool}'. Available tools are: ${services}" 1
fi

info "Setting up tree structures and symlinks for ${tool} version ${version}"
mkdir -p "${DIR}/${tool}/${tool}-${version}/usr/bin"
mkdir -p "${DIR}/${tool}/root"
mkdir -p "${DIR}/${tool}/logs"
mkdir -p "${DIR}/${tool}/pkgs"
mkdir -p "${DIR}/${tool}/sources"
rm -f "${DIR}/tool"
ln -nfs "${tool}" "${DIR}/tool"
rm -f "${DIR}/${tool}/current"
ln -nfs "${tool}-${version}" "${DIR}/${tool}/current"

if [[ "${CPLX_BIN}" == "true" ]]; then
    mkdir -p "${DIR}/${tool}/bin"
    cp "${DIR}/../echos/echos" "${DIR}/${tool}/bin" || fatal "Failed to copy echos to ${DIR}/${tool}/bin" 1
    ln -nfs "../${tool}-${version}" "${DIR}/${tool}/bin/current"
fi