services=git,python,mpdecimal,openssl
CPLX_CHECK_SRC=libpython3.so
SSH_CONFIG_ENTRY=centos8
hostname=a_hostname
cplx_path=/path/to/cplx
architecture=centos_8_x86_64
CPLX_ARCH_EXT=el8.x86_64
CPLX_CHECK_PREFIX=lib/libpython3.so
