services=git,python,mpdecimal,openssl111,openldap,curl,libpsl,libunistring,libidn2,openssl3,pass,pinentry,libgpg-error,glibc,gcc,flex2,make4,automake116

CPLX_ARCH_EXT=el9.x86_64
q=usr/bin/pldd
CPLX_CHECK_SRC=elf/pldd
SSH_CONFIG_ENTRY=<your ssh entry>
hostname=<your hostname>
cplx_path=/home/<a user>/cplx (or any other folder name or pathname)
architecture=the result of source /etc/os-release; printf "%s_%s_%s" $ID $VERSION_ID $(uname -m)
CPLX_BIN=false
CPLX_CONFIG_DONE=default
